-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4xughac+irUFYa31
h+27cMZ7cVxvkWIBPLJgVciRwGSgCgYIKoZIzj0DAQehRANCAASSdghG38EPKhrP
vbdkNIYkCMsPa+3rQO1bssGRRugjtRhdEsCQ7L4zHVn5Ue3RGdrp1rYvqx8a1KMP
2nlVMLrB
-----END PRIVATE KEY-----