// This file is automatically generated by the version bumping script
// Do not edit manually

class AppVersion {
  static const String version = "1.1.256";
  static const String buildNumber = "332";
  static const String fullVersion = "$version+$buildNumber";
  static const String displayVersion = "Version $version";
}
