// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv3KDcxTbeLCuyh7QVVk-MwxR4fnC96yM',
    appId: '1:626930983094:web:0e1a429bcdf9602f580617',
    messagingSenderId: '626930983094',
    projectId: 'uydosh-cd0fe',
    authDomain: 'uydosh-cd0fe.firebaseapp.com',
    storageBucket: 'uydosh-cd0fe.firebasestorage.app',
    measurementId: 'G-EH9C2VMSD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2_3GcIIQIUPQffXapchtK-o3GeHWXTgQ',
    appId: '1:626930983094:android:d1a48e441d9aafc2580617',
    messagingSenderId: '626930983094',
    projectId: 'uydosh-cd0fe',
    storageBucket: 'uydosh-cd0fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoQ3pSdCHoJPake23diVVLulvdQ9-1AY4',
    appId: '1:626930983094:ios:03b5d6b33684cd72580617',
    messagingSenderId: '626930983094',
    projectId: 'uydosh-cd0fe',
    storageBucket: 'uydosh-cd0fe.firebasestorage.app',
    androidClientId: '626930983094-1fueiq66e29huaibm5nfjsmvjt035fco.apps.googleusercontent.com',
    iosClientId: '626930983094-sb30bts42bs3suojenc9272ocaph02gu.apps.googleusercontent.com',
    iosBundleId: 'com.uydosh.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoQ3pSdCHoJPake23diVVLulvdQ9-1AY4',
    appId: '1:626930983094:ios:ca467a8fbc81cbd2580617',
    messagingSenderId: '626930983094',
    projectId: 'uydosh-cd0fe',
    storageBucket: 'uydosh-cd0fe.firebasestorage.app',
    iosClientId:
        '626930983094-fmdr5eqq8ulo4k9dmqott0tgdd91ukkl.apps.googleusercontent.com',
    iosBundleId: 'com.uydosh.app',
  );
}